// Factory stub for schematic 'my-schematic'
// Generated by `builder new schematic my-schematic`
// Replace this stub with your real schematic logic.

import type { SchematicContext, Tree } from '@angular-devkit/schematics';
import type { MySchematicSchematicInputs } from './schema.d';

export default function mySchematic(options: MySchematicSchematicInputs) {
  return (tree: Tree, _context: SchematicContext): Tree => {
    // TODO: implement schematic 'my-schematic'
    return tree;
  };
}
