// Package newfeature — tsgen.go generates TypeScript .d.ts declaration files
// from schema.json v1 inputs.
//
// ADR-025: hand-rolled strings.Builder (NO text/template — silent-injection risk
// is unacceptable for user-controlled names crossing into typed output).
//
// REQ coverage:
//   - REQ-TG-01..09: full .d.ts codegen contract
//   - REQ-TI-10: PascalCase applied HERE at the interface name level, NOT inside EscapeIdent
//   - REQ-TG-04: property names via EscapeIdent; renamed fields get // original comment
//   - REQ-TG-05: header comment with version but NO timestamp (deterministic builds)
//   - REQ-TG-06: all fields optional (? suffix) — schema v1 has no required concept
//   - REQ-TG-07: enum → union literal
//   - REQ-TG-08: list → Array<T>
package newfeature

import (
	"sort"
	"strings"
	"unicode"

	"github.com/Project-Builder-Schematics/project-builder-cli/internal/shared/tsident"
)

// BuildVersion is injected at link time via -ldflags "-X ...BuildVersion=v1.2.3".
// Defaults to "DEV" when not set (local builds, tests).
// Used in the .d.ts header comment per REQ-TG-05.
var BuildVersion = "DEV"

// GenerateDTS generates a TypeScript .d.ts declaration file from a schema.
// The interface name is derived from schematicName via PascalCase + "SchematicInputs".
// Property names are escaped via tsident.EscapeIdent (REQ-TI-10 boundary).
//
// Returns a byte slice suitable for writing to schema.d.ts.
// Pure function; deterministic; no I/O.
//
// ADR-025: uses strings.Builder exclusively — NO text/template.
func GenerateDTS(schematicName string, schema Schema) ([]byte, error) {
	var b strings.Builder

	// Header comment (REQ-TG-05 — version only, no timestamp).
	b.WriteString("// Auto-generated by builder new — do not edit manually\n")
	b.WriteString("// @builder-cli v")
	b.WriteString(BuildVersion)
	b.WriteString("\n")
	b.WriteString("\n")

	// Interface name: PascalCase(schematicName) + "SchematicInputs" (REQ-TG-02).
	interfaceName := toPascalCase(schematicName) + "SchematicInputs"
	b.WriteString("export interface ")
	b.WriteString(interfaceName)
	b.WriteString(" {")

	if len(schema.Inputs) == 0 {
		// Empty interface on one line (REQ-SJ-03).
		b.WriteString("}\n")
		return []byte(b.String()), nil
	}

	b.WriteString("\n")

	// Sort input names for deterministic output (maps are unordered in Go).
	names := make([]string, 0, len(schema.Inputs))
	for name := range schema.Inputs {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, origName := range names {
		spec := schema.Inputs[origName]

		// Escape the property name via tsident.EscapeIdent (REQ-TG-04).
		escaped := tsident.EscapeIdent(origName)

		// If the name changed, emit an // original comment (REQ-TG-04).
		if escaped != origName {
			b.WriteString("  // original: ")
			b.WriteString(origName)
			b.WriteString("\n")
		}

		// Property line: "  <escaped>?: <TStype>;"
		b.WriteString("  ")
		b.WriteString(escaped)
		b.WriteString("?: ")
		b.WriteString(mapTypeToTS(spec))
		b.WriteString(";\n")
	}

	b.WriteString("}\n")
	return []byte(b.String()), nil
}

// toPascalCase converts a kebab-case or snake_case string to PascalCase.
// Each word segment (split on - and _) is capitalised; segments are joined.
//
// Examples:
//
//	"my-schematic" → "MySchematic"
//	"my_schematic" → "MySchematic"
//	"foo"          → "Foo"
//	"class"        → "Class" (PascalCase of a reserved word is NOT reserved as a name)
func toPascalCase(s string) string {
	var b strings.Builder
	b.Grow(len(s))

	capitaliseNext := true
	for _, r := range s {
		if r == '-' || r == '_' {
			capitaliseNext = true
			continue
		}
		if capitaliseNext {
			b.WriteRune(unicode.ToUpper(r))
			capitaliseNext = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// mapTypeToTS converts a schema.json type string to the corresponding TypeScript
// type annotation (REQ-TG-03 table).
//
// Type mapping:
//
//	string  → string
//	number  → number
//	boolean → boolean
//	enum    → "val1" | "val2" | ... (union literal)
//	list    → Array<T> where T is items.type mapped
//
// Unknown types fall back to "unknown" (conservative; prevents injection).
func mapTypeToTS(spec InputSpec) string {
	switch spec.Type {
	case "string":
		return "string"
	case "number":
		return "number"
	case "boolean":
		return "boolean"
	case "enum":
		// REQ-TG-07: union literal type "val1" | "val2" | ...
		if len(spec.Enum) == 0 {
			return "string" // degenerate case; ValidateSchema catches this earlier
		}
		parts := make([]string, len(spec.Enum))
		for i, v := range spec.Enum {
			parts[i] = `"` + v + `"`
		}
		return strings.Join(parts, " | ")
	case "list":
		// REQ-TG-08: Array<T>
		if spec.Items == nil || spec.Items.Type == "" {
			return "Array<unknown>" // degenerate; ValidateSchema catches
		}
		inner := mapTypeToTS(InputSpec{Type: spec.Items.Type})
		return "Array<" + inner + ">"
	default:
		return "unknown"
	}
}
