// Package events defines the event catalogue for project-builder-cli.
//
// The Event interface is sealed via an unexported marker method (isEvent).
// Only types defined in this package can implement Event, preventing external
// code from forging events into the execution pipeline.
//
// CONTRACT:STUB — behaviour-deferred to /plan #3+
package events

import "time"

// Event is the sealed sum-type interface for all execution events.
// The unexported isEvent() method ensures only types in this package
// can implement Event.
type Event interface {
	isEvent()
}

// EventBase carries common fields embedded anonymously in every event.
// Fields are accessible directly on the concrete type without qualification:
// e.g., fileCreated.Seq, fileCreated.At — no EventBase prefix needed.
type EventBase struct {
	// Seq is a monotonically increasing sequence number per execution stream.
	// Starts at 1 and is set by the engine.
	Seq uint64

	// At is the wall-clock UTC timestamp when the event was emitted.
	At time.Time
}

// LogSource is the named-type enum for LogLine.Source.
//
// Using a named type (not bare string) ensures that only valid LogSource
// constant values can be assigned, making mis-typed sources a compile error.
type LogSource string

const (
	// LogSourceStdout indicates the log line came from the process standard output.
	LogSourceStdout LogSource = "stdout"

	// LogSourceStderr indicates the log line came from the process standard error.
	LogSourceStderr LogSource = "stderr"

	// LogSourceSystem indicates the log line was generated by the engine itself.
	LogSourceSystem LogSource = "system"
)

// InputSchema describes the expected input type for an InputRequested event.
type InputSchema struct {
	// Type is the input kind: "string", "bool", "select", etc.
	Type string

	// Choices lists valid options when Type == "select".
	Choices []string

	// Default is the pre-filled default value, if any.
	Default any
}

// Summary is emitted as a field of Done events to summarise execution results.
type Summary struct {
	FilesCreated  int
	FilesModified int
	FilesDeleted  int
	ScriptsRun    int
	DurationMS    int64
}

// --- 12 concrete event types ---

// FileCreated is emitted when the engine creates a file or directory.
type FileCreated struct {
	EventBase
	Path  string
	IsDir bool
}

// FileModified is emitted when the engine modifies an existing file.
type FileModified struct {
	EventBase
	Path string
}

// FileDeleted is emitted when the engine deletes a file or directory.
type FileDeleted struct {
	EventBase
	Path string
}

// ScriptStarted is emitted before a lifecycle script begins execution.
//
// Sensitive: when true, the Renderer MUST mask Args in output.
type ScriptStarted struct {
	EventBase
	Name      string
	Args      []string
	Sensitive bool // when true, Renderer MUST mask Args
}

// ScriptStopped is emitted after a lifecycle script completes.
type ScriptStopped struct {
	EventBase
	Name     string
	ExitCode int
}

// LogLine carries a single line of output from the execution process.
//
// V2 naming: Source (typed LogSource enum, was Stream), Text (was Line),
// Sensitive added. When Sensitive is true, Renderer MUST NOT echo Text.
type LogLine struct {
	EventBase
	Level     string    // "debug" | "info" | "warn" | "error"
	Source    LogSource // typed enum (stdout / stderr / system)
	Text      string    // the log content
	Sensitive bool      // when true, Renderer MUST NOT echo Text
}

// InputRequested is a bidirectional event requesting user or agent input.
//
// The producer constructs the Reply channel with cap=1, emits this event,
// then awaits a reply via:
//
//	select {
//	case v := <-replyCh:
//	    // process reply
//	case <-ctx.Done():
//	    // handle cancellation
//	}
//
// When Sensitive is true, the Renderer MUST mask the default value display.
// After receiving a reply, the engine MUST emit a paired InputProvided event
// with Sensitive propagated from this event's Sensitive field.
type InputRequested struct {
	EventBase
	Prompt       string
	Schema       InputSchema
	DefaultValue string
	Sensitive    bool
	Reply        chan<- string // send-only; buffered cap=1
}

// InputProvided is the audit event emitted after the engine receives a reply
// to an InputRequested event.
//
// Sensitive is propagated from the matching InputRequested.Sensitive.
// When Sensitive is true, the Renderer MUST mask Value in output.
type InputProvided struct {
	EventBase
	Prompt    string
	Value     string
	Sensitive bool // propagated from originating InputRequested.Sensitive
}

// Progress reports incremental execution progress.
type Progress struct {
	EventBase
	Step  int
	Total int
	Label string
}

// Done is the terminal success event. Exactly one of Done, Failed, or
// Cancelled is emitted per execution stream; the engine closes the channel
// immediately after.
type Done struct {
	EventBase
}

// Failed is the terminal error event. The engine closes the channel
// immediately after emitting Failed.
type Failed struct {
	EventBase
	Err error
}

// Cancelled is the terminal cancellation event, emitted when ctx is
// cancelled before completion. The engine closes the channel immediately after.
type Cancelled struct {
	EventBase
}

// Sealed marker methods — one per concrete type.
// These unexported methods prevent external packages from implementing Event.
func (FileCreated) isEvent()    {}
func (FileModified) isEvent()   {}
func (FileDeleted) isEvent()    {}
func (ScriptStarted) isEvent()  {}
func (ScriptStopped) isEvent()  {}
func (LogLine) isEvent()        {}
func (InputRequested) isEvent() {}
func (InputProvided) isEvent()  {}
func (Progress) isEvent()       {}
func (Done) isEvent()           {}
func (Failed) isEvent()         {}
func (Cancelled) isEvent()      {}
